### ISSUE TITLE
About user interface

### ISSUE THREAD

**Issue by TotomInc** [HexMerchant/HexMerchant.github.io#3]
User interface is not very responsive, you should build your CSS with % instead of px.

**Comment by HexMerchant** [comment]
K will work on that. just learned how to make a radio button tabbed interface that should work better, so I've been building that and replacing the old U.I. I'll change %'s after I've finished the rework

**Comment by TotomInc** [comment]
If you want, I can build a "prototype" user interface. It will be essentially build with Bootstrap.

**Comment by HexMerchant** [comment]
once i figure out how to give permissoin I will thanks

**Comment by HexMerchant** [comment]
Ok I added you as a collabotator xD I finished my remake of the user-interface but had about 5 issues left and tried to solve them all night xD fixed maybe one. Not gonna replace the repo with my new design. I learned a lot about many new elements so I'll consider it a learning experience now.

**Comment by TotomInc** [comment]
Thanks for adding me, I've just push and sync the user-interface prototype, you can find it here : http://hexmerchant.github.io/user-interface/

Look in the source-code, I explain many things.

I can participate actively on your project if you really need help, don't hesitate to ask me anything you want! :)

Btw, where do you live? I'm in France, and perhaps you live in USA so there is a jet lag of approximatively 7 to 11 hours. :)

**Comment by HexMerchant** [comment]
USA is correct. (-7 MST) Thanks for your help. I'll get to work on reading and understanding your source-code. I'll continue to learn and if something gets me stuck for more then 4 hours then I'll definitely seek advice/help.

**Comment by TotomInc** [comment]
Okay, for me it's the night so I think I will not reply for tomorrow. :)

**Comment by HexMerchant** [comment]
Thanks again for the interface. I'll need to spend more time reading about bootstrap and jquery since I've not used those before. I've starting reading up on jquery first to understand how it works more. I did however replace the old U.I and buttons, so you can take a look. it's still messy though. but I think it's an improvement
